image:
  - Visual Studio 2015

install:
  - git clone https://github.com/Reactive-Extensions/RxCpp.git RxCpp

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - set PATH=C:\Qt\5.9\msvc2015\bin;%PATH%

build_script:
  - cd test
  - qmake test.pro
  - nmake

test_script:
  - .\Release\rxtest.exe